name: Deploy to Firebase Hosting on PR

on:
  pull_request:
    paths:
      - 'express-backend/**'
      - 'whats-the-move/**'

jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Backend Deployment
      - name: Backend Deployment
        working-directory: express-backend
        run: echo "Deploying backend changes"
        # Add any backend-specific steps here

      # Frontend Build and Deployment
      - name: Frontend Deployment
        working-directory: whats-the-move
        run: |
          npm install
          npm run build

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HACKUTD24_WHATSTHEMOVE }}'
          projectId: hackutd24-whatsthemove